close all;
%type xing.txt;
%type ying.txt;
%type zing.txt;
%type timing.txt;
xfileID= fopen('xing.txt','r');
yfileID= fopen('ying.txt','r');
zfileID= fopen('zing.txt','r');
%tfileID= fopen('timing.txt','r');
formatSpec='%f';
x= fscanf(xfileID,formatSpec);
y= fscanf(yfileID,formatSpec);
z= fscanf(zfileID,formatSpec);
%t= fscanf(tfileID,formatSpec);
fclose(xfileID);
fclose(yfileID);
fclose(zfileID);
%fclose(tfileID);
xbias=52;
ybias=333;
zbias=252;
%time=t./3600000;
%time = linspace(1, 3600, 1211570);
%time=t./1000;
l=length (x)*0.02;
timex =0:0.02:l;
l=length (y)*0.02;
timey=0:0.02:l;
l=length (z)*0.02
timez=0.0.02:l;
xscale=(x-xbias)./131;
yscale=(y-ybias)./131;
zscale=(z-zbias)./131;

xaxis=cumtrapz(timex,xscale);
yaxis=cumtrapz(timey,yscale);
zaxis=cumtrapz(timez,zscale);

figure;
subplot(3,1,1);
plot(timex,xaxis);
subplot(3,1,2);
plot(timey,yaxis);
subplot(3,1,3);
plot(timez,zaxis);